modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="${license}"
issueTrackerURL="${issues_url}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="Tslat Effects Lib (TEL)"
logoFile="logo.png"
authors="${authors}"
displayTest="IGNORE_SERVER_VERSION"
description='''
${description}
'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
